src/Entity/Order.php
<?php

namespace Tigris\ShopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use Tigris\BaseBundle\Entity\Model\User;
use Tigris\InvoiceBundle\Entity\Invoice;
use Tigris\InvoiceBundle\Invoice\InvoiceItem;
use Tigris\ShopBundle\Entity\User\ShopUserInterface;
use Tigris\ShopBundle\Repository\OrderRepository;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: 'shop_order')]
#[ORM\HasLifecycleCallbacks]
class Order
{
    use TimestampableEntity;
    use SoftDeleteableEntity;

    final public const STATUS_NEW = 'new';
    final public const STATUS_AWAITING = 'awaiting';
    final public const STATUS_FINISHED = 'finished';
    final public const STATUS_SHIPPED = 'shipped';
    final public const STATUS_CANCELED = 'canceled';
    final public const STATUS_AVAILABLE = 'available';

    final public const PAYMENT_STATUS_CANCELED = 'canceled';
    final public const PAYMENT_STATUS_AWAITING_PAYMENT = 'awaiting_payment';
    final public const PAYMENT_STATUS_PAID = 'paid';
    final public const PAYMENT_STATUS_REFUNDED = 'refunded';

    final public const METHOD_BANK_CHECK = 'bank_check';
    final public const METHOD_CASH = 'cash';
    final public const METHOD_CREDIT_CARD = 'credit_card';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $user = null;

    /**
     * @var Collection<OrderProduct>
     */
    #[ORM\OneToMany(targetEntity: OrderProduct::class, mappedBy: 'order', cascade: ['all'], orphanRemoval: true)]
    #[JMS\Exclude]
    private Collection $orderProducts;

    #[ORM\Column(length: 100)]
    private string $firstname = '';

    #[ORM\Column(length: 100)]
    private string $name = '';

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $orderAddressData = [];

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $shippingAddressData = [];

    #[ORM\OneToMany(targetEntity: OrderInvoice::class, mappedBy: 'order', cascade: ['all'])]
    #[JMS\Exclude]
    private Collection $orderInvoices;

    #[ORM\Column(type: Types::JSON, nullable: true)]
    #[JMS\Exclude]
    private ?array $apiResponse = [];

    #[ORM\Column(nullable: true)]
    private ?string $paymentMethod = null;

    #[ORM\Column(type: Types::JSON)]
    #[JMS\SerializedName('transport')]
    private array $transportData = [];

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private string $transportPrice = '0';

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private string $totalPrice = '0';

    #[ORM\Column(type: Types::JSON, nullable: true)]
    #[JMS\Exclude]
    private array $transportServiceData = [];

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $trackingNumber = null;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $shippingService = null;

    #[ORM\OneToMany(targetEntity: OrderStatus::class, mappedBy: 'order', cascade: ['all'])]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[ORM\OrderBy(['createdAt' => 'DESC', 'id' => 'DESC'])]
    private Collection $statuses;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?OrderStatus $paymentStatus = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?OrderStatus $deliveryStatus = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?OrderStatus $status = null;

    #[ORM\OneToMany(targetEntity: OrderDiscount::class, mappedBy: 'order', cascade: ['persist'])]
    private Collection $discounts;

    public function __construct()
    {
        $this->orderProducts = new ArrayCollection();
        $this->orderInvoices = new ArrayCollection();
        $this->statuses = new ArrayCollection();
        $this->discounts = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function prePersist()
    {
        $payStatus = (new OrderStatus())
            ->setType(OrderStatus::PAYMENT)
            ->setStatus(OrderStatus::UNPAID)
            ->setOrder($this)
        ;

        $this->statuses[] = $payStatus;
        $this->paymentStatus = $payStatus;

        $deliStatus = (new OrderStatus())
            ->setType(OrderStatus::DELIVERY)
            ->setStatus(OrderStatus::SHIPPING)
            ->setOrder($this)
        ;

        $this->statuses[] = $deliStatus;
        $this->deliveryStatus = $deliStatus;

        $status = (new OrderStatus())
            ->setType(OrderStatus::ORDER)
            ->setStatus(OrderStatus::OPEN)
            ->setOrder($this)
        ;

        $this->statuses[] = $status;
        $this->status = $status;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        if ($user instanceof ShopUserInterface) {
            $address = $user->getMainAddress();

            if ($address instanceof Address) {
                $this->setOrderAddress($address);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<OrderProduct>
     */
    public function getOrderProducts(): Collection
    {
        return $this->orderProducts;
    }

    public function setOrderProducts(Collection $orderProducts): self
    {
        $this->orderProducts = $orderProducts;

        return $this;
    }

    public function addOrderProduct(OrderProduct $orderProduct): self
    {
        if (!$this->orderProducts->contains($orderProduct)) {
            $orderProduct->setOrder($this);
            $this->orderProducts->add($orderProduct);
        }

        return $this;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function addProduct(Product $product, int $quantity = 1): self
    {
        foreach ($this->orderProducts as $orderProduct) {
            if ($orderProduct->getProduct()->getId() == $product->getId()) {
                $orderProduct->setQuantity($orderProduct->getQuantity() + $quantity);

                return $this;
            }
        }

        $orderProduct = (new OrderProduct())
            ->setOrder($this)
            ->setProduct($product)
            ->setQuantity($quantity)
        ;

        $this->orderProducts[] = $orderProduct;

        return $this;
    }

    public function setProductGiftWrappingOption(Product $product, bool $enable, float $price = 0, ?Tax $tax = null): self
    {
        foreach ($this->orderProducts as $orderProduct) {
            if ($orderProduct->getProduct()->getId() == $product->getId()) {
                $orderProduct
                    ->setGiftWrappingOption($enable)
                    ->setGiftWrappingPrice($price)
                    ->setGiftWrappingTaxValue($tax->getValue())
                ;

                return $this;
            }
        }

        return $this;
    }

    public function resetProducts(): self
    {
        $this->orderProducts = new ArrayCollection();

        return $this;
    }

    #[JMS\VirtualProperty]
    public function getPrice(bool $withTransport = true, bool $withDiscount = true, ?User $user = null, bool $withOrderDiscount = true, bool $withGiftOption = true): float
    {
        if (!$user instanceof User) {
            $user = $this->getUser();
        }

        $price = 0.0;
        foreach ($this->orderProducts as $orderProduct) {
            $productPrice = $orderProduct->getPrice($withDiscount, $withGiftOption);
            $price += $productPrice * $orderProduct->getQuantity();
        }

        // Order discounts
        if ($withOrderDiscount) {
            foreach ($this->discounts as $orderDiscount) {
                $price -= $orderDiscount->getPriceValue();
            }
        }

        // Transport allways add at the end
        if ($this->getTransport() instanceof Transport && $withTransport) {
            $price += $this->getTransportPrice();
        }

        return round($price, 2);
    }

    public function getItemsETPrice(): float
    {
        $price = 0.0;
        foreach ($this->orderProducts as $orderProduct) {
            $productPrice = $orderProduct->getETPrice();
            $price += $productPrice * $orderProduct->getQuantity();
        }

        return $price;
    }

    public function getOrderAddress(): ?Address
    {
        if ($this->orderAddressData === null || $this->orderAddressData === []) {
            return null;
        }

        return (new Address())
            ->setName($this->name)
            ->setFirstname($this->firstname)
            ->fromArray($this->orderAddressData)
        ;
    }

    public function setOrderAddress(Address $orderAddress): self
    {
        $this->name = $orderAddress->getName();
        $this->firstname = $orderAddress->getFirstname();

        $this->orderAddressData = $orderAddress->toArray();

        return $this;
    }

    public function getShippingAddress(): ?Address
    {
        if ($this->shippingAddressData === null || $this->shippingAddressData === []) {
            return $this->getOrderAddress();
        }

        return (new Address())
            ->setName($this->name)
            ->setFirstname($this->firstname)

src/Entity/OrderDiscount.php
<?php

namespace Tigris\ShopBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Tigris\ShopBundle\Utils\Calculator\Calculator;

#[ORM\Entity]
#[ORM\Table(name: 'shop_order_discount')]
class OrderDiscount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'discounts')]
    private Order $order;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    #[JMS\Exclude]
    private ?Discount $discount = null;

    #[ORM\Column(type: Types::JSON)]
    #[JMS\Exclude]
    private array $discountData = [];

    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2)]
    private string $value;

    #[ORM\Column(length: 20)]
    private string $type;

    #[ORM\Column(length: 180)]
    private string $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrder(): ?Order
    {
        return $this->order;
    }

    public function setOrder(?Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    public function getDiscount(): Discount
    {
        return (new Discount())->fromArray($this->discountData);
    }

    public function setDiscount(Discount $discount): self
    {
        $this->discount = $discount;
        $this->discountData = $discount->toArray();
        $this->value = $discount->getValue();
        $this->type = $discount->getType();
        $this->name = $discount->getName();

        return $this;
    }

    public function setDiscountData(array $data): self
    {
        $this->discountData = $data;

        return $this;
    }

    public function getDiscountData(): array
    {
        return $this->discountData;
    }

    public function getValue(): float
    {
        return (float) ($this->value ?? 0);
    }

    public function setValue(float $value): self
    {
        $this->value = (string) $value;

        return $this;
    }

    public function getPriceValue(): float
    {
        $price = 0.0;
        $orderPrice = $this->order->getPrice(false, true, null, false);

        return match ($this->type) {
            Discount::DISCOUNT_TYPE_PERCENT => Calculator::percent($orderPrice, $this->value),
            Discount::DISCOUNT_TYPE_VALUE => min($orderPrice, $this->value),
            Discount::DISCOUNT_TYPE_NEW_PRICE => $price - $this->value,
            default => $price,
        };
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNewOrderPrice(): float
    {
        $price = $this->order->getPrice(false, true, null, false);

        return match ($this->type) {
            Discount::DISCOUNT_TYPE_PERCENT => max($price - Calculator::percent($price, $this->value), 0),
            Discount::DISCOUNT_TYPE_VALUE => max(0, $price - $this->value),
            Discount::DISCOUNT_TYPE_NEW_PRICE => $price - ($price - $this->value),
            default => $price,
        };
    }
}

templates/purchase/canceled.html.twig
{% extends '@TigrisBase/layout.html.twig' %}

{% block main %}
<div class="card">
    <div class="card-body">
        <div class="h1 text-danger">{{ 'shop.purchase.cancel.title'|trans|parse_icons }}</div>
        <p>{{ 'shop.purchase.cancel.message'|trans }}</p>
    </div>
</div>
{% endblock %}

templates/purchase/delivery.html.twig
{% extends '@TigrisBase/layout.html.twig' %}
{% block main %}
<div id="shop">
    <h1>{{ 'shop.purchase.delivery.title'|trans }}</h1>
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
    
    {% endembed %}
</div>
{% endblock %}

templates/purchase/error.html.twig
{% extends '@TigrisBase/layout.html.twig' %}

{% block main %}
<div class="card">
    <div class="card-body">
        <div class="h1 text-error">{{ 'shop.purchase.error.title'|trans|parse_icons }}</div>
        <p>{{ 'shop.purchase.error.message'|trans }}</p>
    </div>
</div>
{% endblock %}

templates/purchase/finished.html.twig
{% extends '@TigrisBase/layout.html.twig' %}

{% block main %}
<div class="card">
    <div class="card-body">
        <div class="h1 text-success">{{ 'shop.purchase.finished.title'|trans|parse_icons }}</div>
        <p>{{ 'shop.purchase.finished.success'|trans }}</p>
        <a href="{{ path('tigris_shop_order_show', {'id': order.id }) }}" class="btn btn-primary">{{ 'shop.order.show'|trans|parse_icons }}</a>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
if (typeof fbq === 'function') {
    fbq('track', 'Purchase', {
        value: {{ order.price }},
        currency: 'EUR',
    });
}

</script>
{% endblock %}

templates/purchase/index.html.twig
{% extends app.request.xmlHttpRequest 
    ? '@TigrisBase/ajax-layout.html.twig'
    : '@TigrisBase/layout.html.twig' %}
{% block main %}
<div id="shop">
    <h1>{{ 'shop.purchase.address'|trans }}</h1>
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
        {% block body %}
        <div class="row">
            <div class="col-md-5">
                <div id="purchase-addresses">
                    {{ form_row(form.addresses) }}
                </div>
            </div>

            <div class="col-md-7">
                <div id="purchase-new-address">
                {% if form.address is defined %}
                {% include '@TigrisShop/address/_form.html.twig' with {'form': form.address} %}
                {% endif %}
                </div>
            </div>
        </div>
        {% endblock %}
    {% endembed %}
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
window.addEventListener('load', () => {  
    const els = document.querySelectorAll('#purchase-new-address input, #purchase-new-addresses select');
    const radios = document.querySelectorAll('#purchase-addresses input[type="radio"]');
    for(const radio of radios) {
        radio.addEventListener('change', (e) => {
            if (e.target.checked && e.target.id == 'addresses1') {
                els.forEach(function(item) {
                    item.removeAttribute('disabled');
                });
            } else {
                els.forEach(function(item) {
                    item.setAttribute('disabled', true);
                });
            }
        })
    }
})  

</script>
{% endblock %}

templates/purchase/paidatshop.html.twig
{% extends '@TigrisBase/layout.html.twig' %}
{% block main %}
<div id="shop">
    <h1>{{ 'shop.pay_at_shop.title'|trans }}</h1>
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
    {% block body %}
    {{ 'shop.pay_at_shop.message'|trans({'%amount%': (order.price|format_currency('EUR'))})|raw }}
    {% endblock %}
    {% endembed %}
</div>
{% endblock %}

templates/purchase/payment.html.twig
{% extends app.request.xmlHttpRequest 
    ? '@TigrisBase/ajax-layout.html.twig'
    : '@TigrisBase/layout.html.twig' %}

{% block header %}
{% endblock %}

{% block body %}
<div class="d-flex">
    <div class="text-center justify-content-center align-items-center">
        <p class="lead display-4">{{ 'shop.payment.payment_redirection'|trans }}</p>
        <div class="progress">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
        </div>

        <form action="{{ url }}" method="post">
        {% for name, value in fields %}
            <input type="hidden" name="{{ name }}" value="{{ value }}">
        {% endfor %}
        </form>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block javascripts %}
<script>
window.setTimeout(()=>{
    let form = document.querySelector("form");
    form.submit();
},2000);
</script>
{% endblock %}

templates/purchase/summary.html.twig
{% extends app.request.xmlHttpRequest 
    ? '@TigrisBase/ajax-layout.html.twig'
    : '@TigrisBase/layout.html.twig' %}
{% block main %}
<div id="shop">
    <h1>{{ 'shop.purchase.summary'|trans }}</h1>
    {% embed '@TigrisBase/decorators/_card.html.twig' %}
    {% block body %}
        <div class="order-addresses">
            {% if basket.orderAddress is not empty %}
            <div class="invoice-address">
                <h3>{{ 'shop.purchase.address'|trans }}</h3>
                {{ basket.orderAddress.toHtml|raw }}
            </div>
            {% endif %}
            {% if basket.shippingAddress is not empty %}
            <div class="shipping-address">
                <h3>{{ 'shop.purchase.shipping_address'|trans }}</h3>
                {{ basket.shippingAddress.toHtml|raw }}
            </div>
            {% endif %}
        </div>
        {% for basketProduct in basket.basketProducts %}
            {% if basketProduct.quantity > 0 %}
            <div class="row mt-4 order-item">
                <div class="col-8">
                    <div class="product-title">{{ basketProduct.product.name }}</div>
                    
                    {{ 'shop.product.price'|trans }}: {{ basketProduct.product.price|format_currency("EUR") }}<br/>
                    {{ 'shop.basket.quantity'|trans }}: {{ basketProduct.quantity }}
                </div>
                <div class="col-4 text-end">
                    {{ basketProduct.price|format_currency("EUR") }}
                </div>
            </div>
            {% if basketProduct.product.discounts is not empty %} 
            {% for discount in basketProduct.product.discounts %}
                {% if discount.isValid(basketProduct.product, app.user) %}
                <div class="row">
                    <div class="col-8">
                        <div class="product-title">{{ 'shop.discount.discount'|trans }}: {{ discount.name }}</div>
                    </div>
                    <div class="col-4 text-end">
                        -{{ (discount.getDiscount(basketProduct.product, app.user) * basketProduct.quantity)|format_currency("EUR") }}
                    </div>
                </div>
                {% endif %}
            {% endfor %}
            {% endif %}

            {# GIFT WRAPPING OPTION #}
            {% if is_granted(constant('Tigris\\ShopBundle\\Security\\ShopVoter::GIFT_WRAPPING_OPTION')) and basketProduct.giftWrappingOption %}
            <div class="row">
                <div class="col-8">
                    {{ 'shop.gift.gift_options'|trans|parse_icons }}                
                </div>
                <div class="col-4 text-end">
                    {{ basketProduct.giftWrappingPrice|format_currency("EUR") }}
                </div>
            </div>
            {% endif %}
            {# /GIFT WRAPPING OPTION #}
            {% endif %}
                {% if loop.last %}
                <hr/>
                {% if basket.order.discounts is not empty %} 
                <div class="row">
                    {% for discount in basket.order.discounts %}
                    <div class="col-8">
                        <div class="product-title">{{ 'shop.discount.discount'|trans }}: {{ discount.name }}</div>
                    </div>
                    <div class="col-4 text-end">
                        -{{ discount.priceValue|format_currency("EUR") }}
                    </div>
                    {% endfor %}
                </div>
                
                {% endif %}
                {# TRANSPORT #}
                {% if basket.order.transport is not empty %}
                <div class="row">
                    <div class="col-8">
                        <div><strong>{{ basket.order.transport.name }}</strong></div>
                        {% if basket.order.transport.service == constant('SERVICE_MONDIAL_RELAY', basket.order.transport) %}
                        <div>
                            {% include '@TigrisShop/components/_mondial_relay_point.html.twig' with {'data': basket.order.transportServiceData} %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-4 text-end">
                    {% if basket.order.transportPrice == 0 %}
                        <span class="free">{{ "shop.transport.free"|trans }}</span>
                    {% else %}
                        {{ basket.order.transportPrice|format_currency("EUR") }}
                    {% endif %}
                    </div>
                </div>
                {% endif %}
                {# /TRANSPORT #}
                <hr/>
                <div class="row">
                    <div class="col-8">
                        <div class="text-end"><strong>{{ 'shop.basket.total'|trans }}</strong></div>
                    </div>
                    <div class="col-4 text-end">
                        <strong>{{ basket.order.price|format_currency("EUR") }}</strong>
                    </div>
                </div>
                {% endif %}
            
        {% endfor %}
        <hr/>
        <div class="d-flex justify-content-between">
            <div>
                {% for name, method in paymentMethods %}
                    {% if not method.test or (method.test and is_granted('ROLE_ADMIN')) or app.debug %}
                        <a href="{{ path('tigris_shop_purchase_payment', {'type': name}) }}" class="btn btn-primary btn-{{ name }} btn-icon me-3">{{ ('shop.button.'~name)|trans|parse_icons }}{% if method.test %}
                        <br/>TEST !
                        {% endif %}</a>
                        
                    {% endif %}
                {% endfor %}
                {% set clickCollectconfig = configs.getGroupValue('TigrisShopBundle.clickcollect') %}
                {% if basket.order.transport is not empty and basket.order.transport.type == 'collect' and clickCollectconfig.payAtShop is defined and clickCollectconfig.payAtShop %}
                    <a href="{{ path('tigris_shop_purchase_paidatshop') }}" class="btn btn-secondary btn-icon">{{ 'shop.button.pay_at_shop'|trans|parse_icons }}</a>
                {% endif %}
            </div>
            <div>
                <h4>{{ 'shop.discount.code'|trans }}</h4>
                <tigris-shop-discount-code></tigris-shop-discount-code>
            </div>
        </div>
    {% endblock %}
    {% endembed %}
</div>
{% endblock %} 