src/Entity/Basket.php
<?php

namespace Tigris\ShopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Tigris\BaseBundle\Entity\Model\User;

#[ORM\Entity]
#[ORM\Table(name: 'shop_basket')]
class Basket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int|null $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private User $user;

    /**
     * @var Collection<BasketProduct>
     */
    #[ORM\OneToMany(targetEntity: BasketProduct::class, mappedBy: 'basket', cascade: ['all'], orphanRemoval: true)]
    private Collection $basketProducts;

    #[ORM\OneToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private Order|null $order = null;

    /**
     * @var Collection<Discount>
     */
    #[ORM\ManyToMany(targetEntity: Discount::class)]
    #[ORM\JoinTable(name: 'shop_basket_discount')]
    private Collection $discounts;

    public function __construct()
    {
        $this->basketProducts = new ArrayCollection();
        $this->discounts = new ArrayCollection();
    }

    public function getId(): int|null
    {
        return $this->id;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBasketProducts(): Collection
    {
        return $this->basketProducts;
    }

    public function getBasketProduct(Product $product)
    {
        foreach ($this->basketProducts as $basketProduct) {
            if ($basketProduct->getProduct()->getId() == $product->getId()) {
                return $basketProduct;
            }
        }

        return null;
    }

    public function setBasketProducts(Collection $basketProducts): self
    {
        $this->basketProducts = $basketProducts;

        return $this;
    }

    public function addProduct(Product $product, int $quantity = 1): self
    {
        if (Product::TYPE_VIRTUAL != $product->getType()) {
            $quantity = min($quantity, $product->getQuantity());
        }

        foreach ($this->basketProducts as $basketProduct) {
            if ($basketProduct->getProduct()->getId() == $product->getId()) {
                $basketProduct->setQuantity($basketProduct->getQuantity() + $quantity);

                return $this;
            }
        }

        $basketProduct = (new BasketProduct())
            ->setBasket($this)
            ->setProduct($product)
            ->setQuantity($quantity)
        ;

        $this->basketProducts[] = $basketProduct;

        return $this;
    }

    /**
     * @return array<Product>
     */
    public function getProducts(): array
    {
        $products = [];
        foreach ($this->basketProducts as $basketProduct) {
            $products[] = $basketProduct->getProduct();
        }

        return $products;
    }

    public function changeQuantity(Product $product, $quantity)
    {
        foreach ($this->basketProducts as $basketProduct) {
            if ($basketProduct->getProduct()->getId() === $product->getId()) {
                if ($quantity > 0) {
                    $basketProduct->setQuantity($quantity);
                } else {
                    $this->basketProducts->removeElement($basketProduct);
                }

                return $this;
            }
        }
        return null;
    }

    public function removeProduct(Product $product): self
    {
        foreach ($this->basketProducts as $basketProduct) {
            if ($basketProduct->getProduct()->getId() == $product->getId()) {
                $this->basketProducts->removeElement($basketProduct);

                return $this;
            }
        }

        return $this;
    }

    public function getPrice(User $user = null): float
    {
        $price = 0.0;
        foreach ($this->basketProducts as $basketProduct) {
            $price += $basketProduct->getPrice(true, $user, true);
        }

        return $price;
    }

    public function hasDelivery(): bool
    {
        foreach ($this->basketProducts as $basketProduct) {
            if (Product::TYPE_STANDARD == $basketProduct->getProduct()->getType()) {
                return true;
            }
        }

        return false;
    }

    public function getProductCount(): int
    {
        return count($this->basketProducts);
    }

    public function getShippingAddress()
    {
        return $this->order->getShippingAddress();
    }

    public function getOrderAddress(): Address
    {
        return $this->order->getOrderAddress();
    }

    public function getProductsQuantity()
    {
        $quantity = 0;
        foreach ($this->basketProducts as $bp) {
            $quantity += $bp->getQuantity();
        }

        return $quantity;
    }

    public function getProductQuantity(Product $product)
    {
        foreach ($this->basketProducts as $bp) {
            if ($bp->getProduct()->getId() == $product->getId()) {
                return $bp->getQuantity();
            }
        }

        return 0;
    }

    public function getOrder(): null|Order
    {
        return $this->order;
    }

    public function setOrder(null|Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    public function getWeight()
    {
        $w = 0;
        foreach ($this->basketProducts as $basketProduct) {
            $w += $basketProduct->getWeight();
        }

        return $w;
    }

    public function getMaxWidth()
    {
        $maxWidth = 0;
        foreach ($this->basketProducts as $basketProduct) {
            $maxWidth = max($maxWidth, $basketProduct->getProduct()->getMaxWidth());
        }

        return $maxWidth;
    }

    public function getMaxHeight()
    {
        $maxHeight = 0;
        foreach ($this->basketProducts as $basketProduct) {
            $maxHeight = max($maxHeight, $basketProduct->getProduct()->getMaxHeight());
        }

        return $maxHeight;
    }

    public function getMaxDepth()
    {
        $maxDepth = 0;
        foreach ($this->basketProducts as $basketProduct) {
            $maxDepth = max($maxDepth, $basketProduct->getProduct()->getMaxDepth());
        }

        return $maxDepth;
    }

    /**
     * Return the total transport price majoration (product added price).
     */
    public function getDeliveryAddedPrice(): float
    {
        $addedPrice = 0;
        foreach ($this->basketProducts as $basketProduct) {
            $addedPrice += ($basketProduct->getProduct()->getDeliveryAddedPrice() * $basketProduct->getQuantity());
        }

        return $addedPrice;
    }

    /**
     * Return unavailable transport for one or more product.
     */
    public function getExcludeTransports(): ArrayCollection
    {
        $excludeTransports = new ArrayCollection();

        foreach ($this->basketProducts as $basketProduct) {
            $product = $basketProduct->getProduct();
            foreach ($product->getUseTransports() as $transport) {
                if (!$excludeTransports->contains($transport)) {
                    $excludeTransports->add($transport);
                }
            }
        }

        return $excludeTransports;
    }

    public function getDiscounts(): Collection
    {
        return $this->discounts;
    }

    public function addDiscount(Discount $discount): self
    {
        if (!$this->discounts->contains($discount) && Discount::ITEM_TYPE_ORDER === $discount->getItemType()) {
            $this->discounts[] = $discount;
        }

        return $this;
    }

    public function changeGiftWrappingOption(Product $product, bool $enable, float $price, Tax $tax): self
    {
        foreach ($this->basketProducts as $basketProduct) {
            if ($basketProduct->getProduct()->getId() === $product->getId()) {
                $basketProduct
                    ->setGiftWrappingOption($enable)
                    ->setGiftWrappingPrice($price)
                    ->setGiftWrappingTaxValue($tax->getValue())
                ;

                return $this;
            }
        }
    }
}

src/Entity/OrderDiscount.php
<?php

namespace Tigris\ShopBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Tigris\ShopBundle\Utils\Calculator\Calculator;

#[ORM\Entity]
#[ORM\Table(name: 'shop_order_discount')]
class OrderDiscount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'discounts')]
    private Order $order;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    #[JMS\Exclude]
    private ?Discount $discount = null;

    #[ORM\Column(type: Types::JSON)]
    #[JMS\Exclude]
    private array $discountData = [];

    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2)]
    private string $value;

    #[ORM\Column(length: 20)]
    private string $type;

    #[ORM\Column(length: 180)]
    private string $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrder(): ?Order
    {
        return $this->order;
    }

    public function setOrder(?Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    public function getDiscount(): Discount
    {
        return (new Discount())->fromArray($this->discountData);
    }

    public function setDiscount(Discount $discount): self
    {
        $this->discount = $discount;
        $this->discountData = $discount->toArray();
        $this->value = $discount->getValue();
        $this->type = $discount->getType();
        $this->name = $discount->getName();

        return $this;
    }

    public function setDiscountData(array $data): self
    {
        $this->discountData = $data;

        return $this;
    }

    public function getDiscountData(): array
    {
        return $this->discountData;
    }

    public function getValue(): float
    {
        return (float) ($this->value ?? 0);
    }

    public function setValue(float $value): self
    {
        $this->value = (string) $value;

        return $this;
    }

    public function getPriceValue(): float
    {
        $price = 0.0;
        $orderPrice = $this->order->getPrice(false, true, null, false);

        return match ($this->type) {
            Discount::DISCOUNT_TYPE_PERCENT => Calculator::percent($orderPrice, $this->value),
            Discount::DISCOUNT_TYPE_VALUE => min($orderPrice, $this->value),
            Discount::DISCOUNT_TYPE_NEW_PRICE => $price - $this->value,
            default => $price,
        };
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNewOrderPrice(): float
    {
        $price = $this->order->getPrice(false, true, null, false);

        return match ($this->type) {
            Discount::DISCOUNT_TYPE_PERCENT => max($price - Calculator::percent($price, $this->value), 0),
            Discount::DISCOUNT_TYPE_VALUE => max(0, $price - $this->value),
            Discount::DISCOUNT_TYPE_NEW_PRICE => $price - ($price - $this->value),
            default => $price,
        };
    }
}

src/Entity/OrderStatus.php
<?php

namespace Tigris\ShopBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Symfony\Contracts\Translation\TranslatorInterface;

#[ORM\Entity]
#[ORM\Table(name: 'shop_order_status')]
class OrderStatus implements \Stringable
{
    final public const TYPE_SUCCESS = 'success';
    final public const TYPE_WARNING = 'warning';
    final public const TYPE_DANGER = 'danger';
    final public const TYPE_INFO = 'info';
    final public const TYPE_DEFAULT = 'default';

    final public const PAYMENT = 'payment';
    final public const ORDER = 'order';
    final public const DELIVERY = 'delivery';

    final public const OPEN = 'open';
    final public const CONFIRMED = 'confirmed';
    final public const COMPLETED = 'completed';
    final public const CANCELED = 'canceled';

    final public const UNPAID = 'unpaid';
    final public const FAILED = 'failed';
    final public const EXPIRED = 'expired';
    final public const PAID = 'paid';
    final public const REFUNDING = 'refunding';
    final public const REFUNDED = 'refunded';

    final public const UNFULFILLED = 'unfulfilled';
    final public const SHIPPING = 'shipping';
    final public const SHIPPED = 'shipped';
    final public const ARRIVED = 'arrived';
    final public const COLLECTED = 'collected';
    final public const RETURNING = 'returning';
    final public const RETURNED = 'returned';
    final public const AVAILABLE = 'available';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int|null $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private \DateTimeInterface|null $createdAt;

    #[ORM\Column(length: 30)]
    private string $status;

    #[ORM\Column(length: 30)]
    private string $type;

    #[ORM\ManyToOne(inversedBy: 'statuses')]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private Order $order;

    #[JMS\Exclude]
    private TranslatorInterface|null $translator = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): int|null
    {
        return $this->id;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt = null)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus(string $status)
    {
        $this->status = $status;

        return $this;
    }

    public function getOrder()
    {
        return $this->order;
    }

    public function setOrder(Order $order)
    {
        $this->order = $order;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType(string $type)
    {
        $this->type = $type;

        return $this;
    }

    public function getTranslator()
    {
        return $this->translator;
    }

    public function setTranslator(TranslatorInterface $translator)
    {
        $this->translator = $translator;

        return $this;
    }

    #[JMS\VirtualProperty]
    public function getTrans()
    {
        if ($this->translator instanceof TranslatorInterface) {
            return $this->translator->trans('shop.order.status.'.$this->getStatus());
        }

        return $this->getStatus();
    }

    public function __toString(): string
    {
        return $this->status;
    }

    #[JMS\VirtualProperty]
    public function getColorType()
    {
        return match ($this->status) {
            self::CANCELED, self::FAILED => self::TYPE_DANGER,
            self::COMPLETED, self::SHIPPED, self::AVAILABLE, self::PAID => self::TYPE_SUCCESS,
            self::SHIPPING, self::UNPAID, self::OPEN => self::TYPE_WARNING,
            self::CONFIRMED => self::TYPE_INFO,
            default => self::TYPE_DEFAULT,
        };
    }
}

src/Controller/OrderController.php
<?php

namespace Tigris\ShopBundle\Controller;

use Tigris\ShopBundle\Entity\Transport;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Tigris\BaseBundle\Controller\BaseController;
use Tigris\ShopBundle\Entity\Order;
use Tigris\ShopBundle\Manager\ShopManager;
use Tigris\ShopBundle\TransportService\TransportServices;

#[Route(path: '/shop/order')]
#[IsGranted('ROLE_USER')]
class OrderController extends BaseController
{
    #[Route(path: '/list.{_format}', defaults: ['_format' => 'html'], options: ['expose' => true])]
    public function index(Request $request, ShopManager $shopManager, $_format): Response
    {
        if ('json' == $_format) {
            $criteria = $this->getCriteria($request);

            $entities = $shopManager->findOrderByUser($this->getUser(), $criteria);

            return $this->paginatorToJsonResponse($entities);
        }

        return $this->render('@TigrisShop/order/index.html.twig');
    }

    #[Route(path: '/{id}', options: ['expose' => true])]
    public function show(Order $entity, TransportServices $transportServices): Response
    {
        $this->denyAccessUnlessGranted('view', $entity);

        $transport = $entity->getTransport();

        $transportService = null;
        if ($transport instanceof Transport) {
            $serviceName = $transport->getService();
            $transportService = $transportServices->getService($serviceName);
        }

        return $this->render(
            '@TigrisShop/order/show.html.twig',
            ['entity' => $entity, 'transportService' => $transportService]
        );
    }
}

templates/order/_details.html.twig
{% if returnRoute is not defined %}
{% set returnRoute = 'tigris_shop_order_index' %}
{% endif %}
<div class="order-show" id="shop">
    <div class="d-flex justify-content-between align-items-center">
        {% if entity.orderInvoices|length > 0 %}
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdown-invoice" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ 'shop.order.invoices'|trans }}
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-invoice">
                {% for orderInvoice in entity.orderInvoices %}
                <button-action route="tigris_invoice_invoice_show" :route-params="{'id': {{ orderInvoice.invoice.id }} }" :modal="true" class="dropdown-item" >{{ 'shop.order.invoice'|trans({"%n%": loop.index }) }}</button-action>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
    {% embed '@TigrisBase/decorators/_card.html.twig' %}
    {% block header %}
    <div>
        <div class="order-label">{{ 'shop.order.date'|trans }}</div>
        {{ entity.createdAt|format_datetime('full', 'short') }}
    </div>
    <div>
        <div class="order-label">{{ 'shop.order.total'|trans }}</div>
        {{ entity.price|format_currency('EUR')}}
    </div>
    {% endblock %}
    {% block body %}
    <div class="order-addresses">
        
        {% if entity.orderAddress is not empty %}
        <address>
            {{ entity.orderAddress.toHtml|raw }}
        </address>
        {% endif %}
        <div>
        {% if entity.transport is not empty and entity.transport.service == 'mondial_relay' %}
            {% include '@TigrisShop/components/_mondial_relay_point.html.twig' with {'data': entity.transportServiceData} %}
        {% endif %}

        {% if entity.trackingNumber is not empty %}
            {% include '@TigrisShop/components/_tracing_button.html.twig' with {'service': transportService, 'code':entity.trackingNumber } %}
        {% endif %}
        </div>
    </div> 

    <div class="d-flex justify-content-between">
        <div>
            <h2>{{ 'shop.product.products'|trans }}</h2>
            {% for orderProduct in entity.orderProducts %}
            <div class="media product-item">
                <div class="media-body">
                    <h3>{{ orderProduct.name }}</h3>
                    {% if orderProduct.tax is not null %}
                    {{ 'shop.product.priceET'|trans }}: <strong>{{ orderProduct.ETPrice|format_currency("EUR") }}</strong><br/>
                    {{ orderProduct.tax }} <strong>{#{{ orderProduct.product.tax.value }}% #}</strong><br/>
                    {% endif %}
                    {{ 'shop.product.priceIT'|trans }}: <strong>{{ orderProduct.price|format_currency("EUR") }}</strong><br/>
                    {{ 'shop.basket.quantity'|trans }}: <strong>{{ orderProduct.quantity }}</strong><br/>
                    {% for discount in orderProduct.discounts %}
                    {{ discount.name }}: <strong>-{{ discount.value|format_currency("EUR") }}</strong><br/>
                    {% endfor %}
                    {% if orderProduct.hasGiftWrappingOption %}
                    {{ 'shop.gift.gift_options'|trans|parse_icons }}: <strong>{{ orderProduct.giftWrappingPrice|format_currency("EUR") }}</strong>
                    {% endif %}
                    {# {{ 'shop.product.priceIT'|trans }}:<strong>{{ orderProduct.price(true)|format_currency("EUR") }}</strong> #}
                </div>
            </div>
            {% endfor %}

            {% for orderDiscount in entity.discounts %}
            <div class="media discount-item">
                <div class="media-body">
                    <h3>{{ orderDiscount.name }}</h3>
                    <strong>-{{ orderDiscount.priceValue|format_currency("EUR") }}</strong>
                </div>
            </div>
            {% endfor %}

            {% if entity.transport is not empty %}
            <div class="media transport">
                <div class="media-body">
                    <h3>{{ entity.transport.name }}</h3>
                    {{ 'shop.product.price'|trans }}: <strong>{{ entity.transportPrice|format_currency("EUR") }}</strong>
                    
                </div>
            </div>
            {% endif %}
        </div>
        <div>
            <ul class="list-unstyled">
                <li>
                    {{ 'shop.order.status.label'|trans }} 
                    <span class="badge bg-{{ entity.status.colorType }}">{{ ('shop.order.status.'~entity.status)|trans }}</span>
                </li>
                <li>
                    {{ 'shop.order.payment_status'|trans }} 
                    <span class="badge bg-{{ entity.paymentStatus.colorType }}">{{ ('shop.order.status.'~entity.paymentStatus)|trans }}</span>
                </li>
                {% if entity.deliveryStatus is not empty %}
                <li>
                    {{ 'shop.order.shipping_status'|trans }} 
                    <span class="badge bg-{{ entity.deliveryStatus.colorType }}">{{ ('shop.order.status.'~entity.deliveryStatus)|trans }}</span>
                </li>
                {% endif %}
            </ul>
                
        </div>
    </div>

    {% endblock %}

    {% block footer %}
    <a class="btn btn-link" href="{{ path(returnRoute) }}">{{ '.icon-arrow-left'|parse_icons }} {{ 'button.return'|trans }}</a>
    {% endblock %}
    {% endembed %}
</div>

templates/order/index.html.twig
{% extends '@TigrisBase/user/my_account_layout.html.twig' %}

{% block content %}
<h1>{{ 'shop.order.user_title'|trans }}</h1>
<tigris-data-list route="tigris_shop_order_index" v-slot="{loadData, entities, filters, totalCount, begin, end, sort, loading}">
<div class="order-list">
    <div class="d-flex justify-content-between my-3">
        <div class="p-2">{{ 'data_count'|trans({'%begin%':'${begin}', '%end%':'${end}', '%total%':'${totalCount}'}) }}</div>
        <pagination></pagination>
    </div>

    <div v-for="entity in entities" :key="entity.id" class="card mb-3" v-cloak>
        <div class="card-body">
            <div class="row w-100">
            
                <div class="d-none d-md-block col-lg-2">
                    <div class="order-label d-inline-block d-lg-block">{{ 'shop.order.date'|trans }}</div>
                    ${ $filters.formatDate(entity.createdAt, 'LL') }
                </div>
                <div class="col-lg-2">
                    <div class="order-label d-inline-block d-lg-block">{{ 'shop.order.total'|trans }}</div>
                    ${ $filters.currency(entity.price) }
                </div>
                <div class="col-lg-2">
                    <div class="order-label d-inline-block d-lg-block">{{ 'shop.order.payment_status'|trans }}</div>
                    <span class="mx-1 badge" :class="'bg-' + entity.paymentStatus.colorType">${ entity.paymentStatus.trans }</span>
                </div>
                <div class="col-lg-2">
                    <div class="order-label d-inline-block d-lg-block">{{ 'shop.order.shipping_status'|trans }}</div>
                    <span class="mx-1 badge" :class="'bg-' + entity.deliveryStatus.colorType">${ entity.deliveryStatus.trans }</span>
                </div>
                <div class="col-lg-4 d-flex justify-content-end align-items-end">
                    <button-action v-if="entity.mainInvoice" class="btn-sm me-1" type="secondary" route="tigris_invoice_invoice_show" :route-params="{id: entity.mainInvoice.id }" :modal="true">{{ 'shop.order.invoice'|trans({"%n%": '' }) }}</button-action>

                    <button-action route="tigris_shop_order_show" class="btn-sm" :route-params="{id: entity.id}" :modal="false" type="primary">
                        <span class="d-none d-md-inline">
                        {{ 'shop.order.show'|trans|parse_icons }}
                        </span>
                        <span class=" d-md-none">
                        {{ '.icon-eye'|parse_icons }}
                        </span>
                        
                    </button-action>
                </div>
            </div>
        </div>
        
    </div>
    <div class="d-flex justify-content-between my-3">
        <div class="p-2">{{ 'data_count'|trans({'%begin%':'${begin}', '%end%':'${end}', '%total%':'${totalCount}'}) }}</div>
        <pagination></pagination>
    </div>
</div>
</tigris-data-list>
{% endblock %}

templates/order/show.html.twig
{% extends '@TigrisBase/layout.html.twig' %}

{% block title %}{{ 'shop.order.number'|trans({'%n%': entity.formattedNumber }) }}{% endblock %}
{% block main %}
<h1>{{ 'shop.order.number'|trans({'%n%': entity.formattedNumber }) }}</h1>
{% include '@TigrisShop/order/_details.html.twig' %}
{% include '@TigrisShop/order_message/_list.html.twig' %}

{% endblock %}